---
title: "R Notebook"
output: html_notebook
---

```{r}
damascus_data <- read.csv('Damascus-OttomanGovernors - Governors.csv', stringsAsFactors=T)
head(damascus_data)
```

```{r}
substrRight <- function(x, n){
  substr(x, nchar(x)-n+1, nchar(x))
}
```

```{r}
xlabels <- substrRight(as.character(damascus_data[1:170,]$Start.Date), 4)
xlabels
```


```{r}
## highlight region data
start <- 1520
end <- 1566
suleiman <- data.frame(start=start, end=end, group=seq_along(start))
```

```{r}
start <- 1789
end <- 1807
selim_iii <- data.frame(start=start, end=end, group=seq_along(start))
```

```{r}
start <- 1623
end <- 1640
murad_iv <- data.frame(start=start, end=end, group=seq_along(start))
```

```{r}
library(stringr)
library(ggplot2)

every_nth = function(n) {
  return(function(x) {x[c(TRUE, rep(FALSE, n - 1))]})
}


a<-ggplot(data=damascus_data[1:170,], aes(x=as.numeric(substrRight(as.character(Start.Date), 4))+10, y=scale(Tenure..Years.))) +
  geom_bar(stat="identity") + 
  #scale_x_discrete(breaks = every_nth(n = 70)) + 
  scale_x_continuous(breaks = scales::pretty_breaks(n = 12)) +
  xlab('Year') +
  ylab('Z Score') + 
  geom_rect(data=suleiman, inherit.aes=FALSE, aes(xmin=start, xmax=end, ymin=-Inf,
                ymax=Inf, group=group), color="transparent", fill="green", alpha=0.3) + 
  geom_rect(data=selim_iii, inherit.aes=FALSE, aes(xmin=start, xmax=end, ymin=-Inf,
                ymax=Inf, group=group), color="transparent", fill="red", alpha=0.3) +
  geom_rect(data=murad_iv, inherit.aes=FALSE, aes(xmin=start, xmax=end, ymin=-Inf,
                ymax=Inf, group=group), color="transparent", fill="orange", alpha=0.3) +
  ggtitle("Z Scores of Governor Tenures in Damascus") + 
  theme(plot.title = element_text(size = 11, face = "bold"))
a
```

```{r}
algiers_data <- read.csv('Algiers-Governors - Variability.csv', stringsAsFactors=T)
head(algiers_data)
```


```{r}
xlabels <- substrRight(as.character(algiers_data[1:86,]$Start.Date), 4)
xlabels
```

```{r}
library(stringr)
library(ggplot2)

every_nth = function(n) {
  return(function(x) {x[c(TRUE, rep(FALSE, n - 1))]})
}


b<-ggplot(data=algiers_data[1:86,], aes(x=as.numeric(substrRight(as.character(Start.Date), 4))+10, y=scale(Years.in.Office))) +
  geom_bar(stat="identity") + 
  #scale_x_discrete(breaks = every_nth(n = 37)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 12)) +
  xlab('Year') +
  ylab('Z Score') + 
  geom_rect(data=suleiman, inherit.aes=FALSE, aes(xmin=start, xmax=end, ymin=-Inf,
                ymax=Inf, group=group), color="transparent", fill="green", alpha=0.3) + 
  geom_rect(data=selim_iii, inherit.aes=FALSE, aes(xmin=start, xmax=end, ymin=-Inf,
                ymax=Inf, group=group), color="transparent", fill="red", alpha=0.3) +  
  geom_rect(data=murad_iv, inherit.aes=FALSE, aes(xmin=start, xmax=end, ymin=-Inf,
                ymax=Inf, group=group), color="transparent", fill="orange", alpha=0.3) +
  
  ggtitle("Z Scores of Governor Tenures in Algeria") + 
  theme(plot.title = element_text(size = 11, face = "bold"))
b
```


```{r}
egypt_data <- read.csv('Cairo-OttomanGovernors - Chron-GovData.csv', stringsAsFactors=T)
tail(egypt_data)
```



```{r}
xlabels <- substrRight(as.character(egypt_data[1:172,]$Start), 4)
xlabels
```

```{r}
library(stringr)
library(ggplot2)

every_nth = function(n) {
  return(function(x) {x[c(TRUE, rep(FALSE, n - 1))]})
}

# Create a named character vector that relates factor levels to colors.
grays = c(alive="gray85", dead="gray65", infected="gray38", sod.dead="black")

c<-ggplot(data=egypt_data[1:171,], aes(x=as.numeric(substrRight(as.character(egypt_data[1:171,]$Start), 4))+10, y=scale(Tenure..years.))) +
  geom_bar(stat="identity") + 
  scale_x_continuous(breaks = scales::pretty_breaks(n = 12)) +
  xlab('Year') +
  ylab('Z Score') + 
  geom_rect(data=suleiman, inherit.aes=FALSE, aes(xmin=start, xmax=end, ymin=-Inf,
                ymax=Inf, group=group), color="transparent", fill="green", alpha=0.3) + 
  geom_rect(data=selim_iii, inherit.aes=FALSE, aes(xmin=start, xmax=end, ymin=-Inf,
                ymax=Inf, group=group), color="transparent", fill="red", alpha=0.3) +  
  geom_rect(data=murad_iv, inherit.aes=FALSE, aes(xmin=start, xmax=end, ymin=-Inf,
                ymax=Inf, group=group), color="transparent", fill="orange", alpha=0.3) +
  
  ggtitle("Z Scores of Governor Tenures in Egypt") +
  theme(plot.title = element_text(size = 11, face = "bold")) + 
  coord_cartesian(clip = "off")
  
c
```

```{r}
legend <- ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, color = Species))+
  geom_point(alpha = 0.3)+
  lims(x = c(0,0), y = c(0,0))+
  theme_void()+
  theme(legend.position = c(0.5,0.5),
        legend.key.size = unit(1, "cm"),
        legend.text = element_text(size =  12),
        legend.title = element_text(size = 15, face = "bold"))+
  guides(colour = guide_legend(override.aes = list(size=8))) + 
  theme(legend.position="top")+
  labs(color = 'Sultan')+
  scale_color_manual(labels = c("Suleiman I", "Murad IV", "Selim III"), values = c("green", "orange","red")) 

legend
```


```{r fig.width=8, fig.height=9}
library(ggpubr)
final <- ggarrange(a,b,c, legend, ncol = 1, nrow = 4)
final
```


```{r}
library(dplyr)
library(tidyverse)
library(ggpubr)
library(rstatix)
```

```{r}
damascus_data <- read.csv('Damascus-OttomanGovernors - Governors.csv', stringsAsFactors=T)
```

```{r}
names(damascus_data)
```


# Damascus

```{r}
subsetA <- damascus_data[-which(damascus_data$Simplest_Fate == ""), ]
subsetA <- subsetA[!is.na(subsetA$Simplest_Fate), ]
subsetA <- subsetA[-which(subsetA$Simplest_Fate == "Unknown"), ]


library(dplyr)
subsetA <- subsetA %>%
  rename(Ethnicity = O.T.NT)

subsetA <- subsetA[-which(subsetA$Ethnicity == ""), ]
subsetA <- subsetA[!is.na(subsetA$Ethnicity), ]
subsetA <- subsetA[-which(subsetA$Ethnicity == "Unknown"), ]

```

```{r}
subsetA$Simplest_Fate <- as.factor(as.character(subsetA$Simplest_Fate))
subsetA$Ethnicity <- as.factor(as.character(subsetA$Ethnicity))
```

```{r}
unique(subsetA$Simplest_Fate)
```
```{r}
unique(subsetA$Ethnicity)
```

```{r}
subsetA$Simplest_Fate <- factor(subsetA$Simplest_Fate, levels = c("Willful violent removal",
                                                                  "Non-violent fate",
                                                                  "Killed in battle"))
```

```{r}
library(lemon)
```


```{r fig.width=6.5, fig.height=6.5}

library(vcd)
#png('mosaic_plot.png')
damascus <- mosaic(~ Simplest_Fate + Ethnicity, 
       data = subsetA,
       zero_size = 1.1,
       shade = TRUE,
       highlighting = "Simplest_Fate", highlighting_fill = c('#A3A500', '#00BF7D', '#F8766D'),
       spacing = spacing_equal(sp = unit(0.8, "lines")),
       gp_varnames = gpar(fontsize = 14, fontface = 2),
       gp_labels = gpar(fontsize = 12))
```

